[project]
name = "seaconfig"
version = "5.0.1"
description = "configuration file manage for seafront"
authors = [{name = "Patrick Hennig", email = "patrick.hennig@uu.se"}]
license = {file = "LICENSE"}

dependencies = [
    "pydantic==2.9.2",
]
